### PR TITLE
DATAP-1451 Restructure the unordered lists in CCDB filters

### PR DESCRIPTION
**Pull request by cdmh219**
According to the Lighthouse report, the way we're structuring the lists in the CCDB filters is a problem. The ul tag should only contain li items directly, and the li items in the list should be direct children of the ul tag. Right now the ul tag contains div tags and the li tags are children of the div tags.

## Additions

-

## Removals

- Parent div element

## Changes

- Root element of AggregateBranch component, from div to li

## Testing

-

## Screenshots
NOTE - Before and After should be the same

BEFORE:
Screenshot 2024-07-17 at 3 05 11 PM

Screenshot 2024-07-17 at 3 05 27 PM

AFTER: 
Screenshot 2024-07-17 at 3 06 26 PM

Screenshot 2024-07-17 at 3 06 38 PM

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Review by flacoman91 — APPROVED** [review]
👍   awesome!  thank you!

**Review by flacoman91 — CHANGES_REQUESTED** [review]
There's a failing cypress test that needs to be fixed. 

https://github.com/cfpb/ccdb5-ui/blob/main/cypress/e2e/common/filters.cy.js#L203

You can either:
1. update the css selector (easier and less work)
2. rewrite it so it uses testing-library style selector (better for readability and less brittle since it targets actual text values)

**Comment by cdmh219** [comment]
Converted PR to draft, as I work on fix for Cypress test

**Comment by cdmh219** [comment]
@flacoman91 @anselmbradford Fixed Cypress test, ready for review again

**Review by flacoman91 — APPROVED** [review]
thanks for the quick turnaround

**Pull request merged**
